In [ ]:
#Support Vector Machine - GridSearchCV Method - GridSearchCV is a automatic algorithm, parameter check and create a table and
#Check & upload the R2 Value automatically in the table.

In [1]:
#Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the dataset
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Categorical data converting into a nominal data
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
#Input\Output Split Method - #Independent - Input in the dataset
independent=dataset[['age','bmi','children','sex_male','smoker_yes']] 
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']] #Dependent - Output in the dataset
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#Training set and Test Set Split Method
from sklearn.model_selection import train_test_split  #Sklearn Supports Machine Learning
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30, random_state=0)

In [9]:
#StandardScaler for better results
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform (X_train)
X_test=sc.transform(X_test)

In [13]:
#Model Creation
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid= {'kernel':['rbf','poly','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid, refit=True, verbose=3, n_jobs=-1)

#Fitting the model for grid search
grid.fit(X_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [14]:
#Print best parameter after tuning
#Print(grid.best_params_)
re=grid.cv_results_
print("The r_score value for best parameter{}:".format(grid.best_params_))

The r_score value for best parameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [17]:
#Table Creation
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.081469,0.016109,0.035844,0.001029,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,35
1,0.049029,0.001063,0.011556,0.001509,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,32
2,0.068504,0.002253,0.013758,0.000506,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,34
3,0.054162,0.005704,0.010506,0.000883,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
4,0.066131,0.002181,0.035610,0.001568,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,36
5,0.051514,0.005372,0.010334,0.000400,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,31
6,0.066948,0.002562,0.013947,0.000284,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,33
7,0.050329,0.002124,0.011295,0.001693,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
8,0.066369,0.001837,0.035525,0.001840,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,29
9,0.061435,0.012628,0.010359,0.000297,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,21
10,0.078406,0.008765,0.015709,0.002905,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,24
11,0.060663,0.002174,0.010477,0.000799,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
12,0.070542,0.002442,0.035331,0.000986,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,30
13,0.058134,0.003105,0.010737,0.000809,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,22
14,0.069877,0.002496,0.014174,0.000427,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,23
15,0.060382,0.000997,0.009906,0.000383,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
16,0.078420,0.001551,0.034250,0.000764,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,12
17,0.076275,0.010587,0.010288,0.000110,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
18,0.076524,0.006706,0.014091,0.001286,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,28
19,0.074581,0.008594,0.010459,0.001154,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
20,0.086788,0.014867,0.035100,0.001317,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,11
21,0.080558,0.017121,0.011031,0.000615,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
22,0.079051,0.004514,0.014021,0.000373,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,27
23,0.068813,0.003572,0.009583,0.000277,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
24,0.086846,0.001853,0.034847,0.000468,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
25,0.126362,0.020196,0.010413,0.000222,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
26,0.074849,0.001754,0.013713,0.000307,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,38
27,0.087630,0.005360,0.009854,0.000482,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
28,0.088056,0.005344,0.035676,0.001806,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
29,0.114716,0.011101,0.011228,0.001240,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
30,0.077552,0.004679,0.013891,0.000456,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,37
31,0.083407,0.003585,0.009761,0.000439,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
32,0.093392,0.003431,0.034011,0.000299,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
33,0.194298,0.087078,0.010155,0.000147,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
34,0.077418,0.003988,0.013731,0.000145,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,39
35,0.101790,0.006422,0.009761,0.000404,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13
36,0.092574,0.004282,0.035274,0.001776,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
37,0.225543,0.099300,0.010453,0.000276,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
38,0.066993,0.010529,0.011858,0.002068,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,40
39,0.085216,0.012481,0.008036,0.002036,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13

In [20]:
#Input

age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [22]:
#Future Prediction

future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(future_prediction))

Future_prediction=[2291197.32936186]