In [1]:
#Support Vector Machine - Without Training set and test set - Split method and StandardScaler for better results

In [2]:
#Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
#Reading the dataset
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
#Categorical data converting into a nominal data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
#Input\Output Split Method - #Independent - Input in the dataset
independent=dataset[['age','bmi','children','sex_male','smoker_yes']] 
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dependent=dataset[['charges']] #Dependent - Output in the dataset
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [7]:
#Model Creation
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid= {'kernel':['rbf','sigmoid','linear'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}

grid=GridSearchCV(SVR(),param_grid, refit=True, verbose=3, n_jobs=-1)

#Fitting the model for grid search
grid.fit(independent,dependent)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'sigmoid', 'linear']},
             verbose=3)

In [8]:
#Print best parameter after tuning
#Print(grid.best_params_)
re=grid.cv_results_
print("The r_score value for best parameter{}:".format(grid.best_params_))

The r_score value for best parameter{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}:

In [9]:
#Table Creation
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.159010,0.002992,0.073616,0.006835,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.113791,-0.110741,-0.079156,-0.103389,-0.106488,-0.102713,0.012303,16
1,0.109300,0.007265,0.023127,0.003079,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
2,0.123391,0.008756,0.019105,0.000081,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
3,0.134077,0.003415,0.077070,0.008577,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.110409,-0.097459,-0.074488,-0.099597,-0.124428,-0.101276,0.016459,15
4,0.144527,0.002200,0.032367,0.001023,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.116743,-0.119312,-0.085214,-0.108210,-0.108716,-0.107639,0.012029,22
5,0.124258,0.008899,0.019492,0.000856,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",-0.018943,0.029886,0.022167,0.003112,-0.066653,-0.006086,0.034672,10
6,0.171272,0.006177,0.072311,0.006545,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",-0.100012,-0.098456,-0.072981,-0.096615,-0.102232,-0.094059,0.010699,14
7,0.097942,0.001226,0.023548,0.004042,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
8,0.241512,0.012998,0.019018,0.000282,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
9,0.130425,0.001588,0.069981,0.003405,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",-0.160182,-0.107253,-0.123430,-0.137753,-0.209551,-0.147634,0.035511,27
10,0.151531,0.004315,0.033609,0.001594,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",-0.142455,-0.160831,-0.117544,-0.137984,-0.130402,-0.137843,0.014263,25
11,0.240979,0.013684,0.020050,0.002250,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.559313,0.521798,0.547691,0.538805,0.508518,0.535225,0.018122,7
12,0.208489,0.008085,0.067724,0.002730,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.080692,-0.054347,-0.062876,-0.079329,-0.117983,-0.079045,0.021865,13
13,0.101587,0.005291,0.021722,0.000750,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
14,0.878280,0.098908,0.019775,0.002341,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
15,0.142284,0.006797,0.070564,0.005030,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.155430,-0.098267,-0.123724,-0.137137,-0.206405,-0.144193,0.036262,26
16,0.155028,0.009152,0.032580,0.000459,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",-2.043140,-2.686121,-2.194563,-2.210858,-1.942521,-2.215441,0.255409,28
17,0.940183,0.127011,0.019110,0.000793,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.736398,0.675162,0.680002,0.699377,0.677952,0.693778,0.022955,1
18,0.284194,0.016541,0.069906,0.005938,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",-0.033126,-0.002835,-0.026545,-0.029140,-0.067392,-0.031808,0.020699,12
19,0.103289,0.006530,0.021662,0.000525,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
20,1.406057,0.133235,0.018857,0.000492,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
21,0.148059,0.007463,0.070827,0.002138,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.143510,-0.087595,-0.113312,-0.128591,-0.193992,-0.133400,0.035492,24
22,0.150112,0.004501,0.034451,0.005087,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-7.209317,-9.282940,-7.776578,-7.745074,-6.891719,-7.781126,0.821557,29
23,1.403531,0.116268,0.018277,0.000620,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.682349,0.630642,0.750714,0.646368,0.722261,0.686467,0.045056,3
24,0.337838,0.026618,0.081935,0.010057,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.011741,0.043659,0.013383,0.021694,-0.012948,0.015506,0.018217,9
25,0.103862,0.007240,0.021630,0.000437,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.115328,-0.113567,-0.081608,-0.106067,-0.107195,-0.104753,0.012107,17
26,2.696396,0.632801,0.019129,0.000568,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5
27,0.157523,0.010226,0.070500,0.004647,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.128958,-0.075578,-0.100199,-0.116051,-0.179304,-0.120018,0.034578,23
28,0.147786,0.004267,0.032543,0.000650,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-15.561853,-20.498908,-17.095474,-16.750877,-15.012168,-16.983856,1.914783,30
29,2.551029,0.574548,0.018058,0.003216,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.677778,0.626814,0.732806,0.633479,0.698692,0.673914,0.039876,5

In [10]:
#Input

age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 30
BMI: 10
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [11]:
#Future Prediction

future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(future_prediction))

Future_prediction=[29164.89672843]

C:\Users\bkann\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(